#create ConfigMap with key and value, which has to be accessed by mysql and  while deploying SpringBoot application
#Define a key value for mysql database, a key value for mysql url used by SpringBoot for connecting to mysql
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-configmap
data:
  serviceone_path: "/sbserviceone/**"
  servicetwo_path: "/sbservicetwo/**"
  serviceone_url: "http://192.168.99.100:31002"
  servicetwo_url: "http://192.168.99.100:31003"

